// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3zmJ5XkJdiMmroVU4ny7ElPY0w7hubN8',
    appId: '1:787461992992:web:27bbcd712bb9b7692e4245',
    messagingSenderId: '787461992992',
    projectId: 'balaagh-mob-web',
    authDomain: 'balaagh-mob-web.firebaseapp.com',
    storageBucket: 'balaagh-mob-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA68UIRxhnjnyfClEqaWpOwTQbhlbP1d0',
    appId: '1:787461992992:android:6acd54a60f1a138c2e4245',
    messagingSenderId: '787461992992',
    projectId: 'balaagh-mob-web',
    storageBucket: 'balaagh-mob-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91IknZcC9-jZteyr0_wapm3csEili24s',
    appId: '1:787461992992:ios:cad820c3eda285f52e4245',
    messagingSenderId: '787461992992',
    projectId: 'balaagh-mob-web',
    storageBucket: 'balaagh-mob-web.appspot.com',
    iosBundleId: 'com.example.balagh',
  );
}
