// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWCVBofhzmv81pd8xLmcMfv-49ObiE6w8',
    appId: '1:157230524967:web:78fdd44216d161a37afc02',
    messagingSenderId: '157230524967',
    projectId: 'store-app-anes2021',
    authDomain: 'store-app-anes2021.firebaseapp.com',
    storageBucket: 'store-app-anes2021.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9C5tkjwJbvH5gEkB-8IgtfY4i81tJ4U',
    appId: '1:157230524967:android:441e4a8f98d141417afc02',
    messagingSenderId: '157230524967',
    projectId: 'store-app-anes2021',
    storageBucket: 'store-app-anes2021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9m3Qe6f_DeqhmoRLEFRj4U9dc0qMrEnc',
    appId: '1:157230524967:ios:d93c147d0f1cdbca7afc02',
    messagingSenderId: '157230524967',
    projectId: 'store-app-anes2021',
    storageBucket: 'store-app-anes2021.appspot.com',
    iosBundleId: 'com.example.balagh',
  );
}
